spring.application.name=HotelBooking
server.port=9090

#MYSQL CONNECTION
Spring.datasource.url=jdbc:postgresql://localhost:5432/HotelBooking
Spring.datasource.username=postgres
Spring.datasource.password=Bdip@8926
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

secreteJwtString=dip123456789dip123456789dip123456789

# Mail configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bdip6333@gmail.com
spring.mail.password=gwzn guue dugl vzjf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true


#THE MAXIMUM SIGN OF IMAGE THAT CAN BE UPLOADED
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

##STRIPE
stripe.api.public.key=pk_test_51R2RHsEKayyO1virM5mOjBise0YDOJgFQbqbfKi9izjUE8TVxl87y1PgqLPvZwrXcquWaaijpvIldS1SwJfYKHma008fChjS8h
stripe.api.secret.key=sk_test_51R2RHsEKayyO1virkUXjTcotSUvekDlpLS5zQ92rZfVpgtNn0M6jQBj057kxNlAUdMeUJlIl8N02knPR1Y7wtFLe000Th8oBH5